In [1]:
import numpy as np

m = np.mat([[1,2,3],[4,5,6]])
print m

[[1 2 3]
 [4 5 6]]


In [2]:
from  numpy import *
import numpy as np

m = np.mat(zeros((3,2)))
print m

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]


In [3]:
# coding=utf-8
import numpy as np

m = np.mat([[1,2,3],[4,5,6]])
print '转置前:\n%s' % m
t = m.T
print '转置前:\n%s' % t

转置前:
[[1 2 3]
 [4 5 6]]
转置前:
[[1 4]
 [2 5]
 [3 6]]


In [4]:
import numpy as np

m1 = np.mat([[1, 2, 3], [4, 5, 6]])
m2 = np.mat([[11, 12, 13], [14, 15, 16]])
print "m1 + m2 = \n%s " % (m1 + m2)

m1 + m2 = 
[[12 14 16]
 [18 20 22]] 


In [5]:
import numpy as np

m1 = np.mat([[1, 2, 3], [4, 5, 6]])
m2 = np.mat([[11, 12], [13, 14], [15, 16]])
print "m1 * m2 = \n%s " % (m1 * m2)

m1 * m2 = 
[[ 82  88]
 [199 214]] 


In [6]:
from numpy import *
import numpy as np

m = np.mat(eye(3,3,dtype=int))
print m

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [7]:
# coding=utf-8
import numpy as np

m = np.mat([[2, 0, 0], [0, 4, 0], [0, 0, 8]])
I = m.I
print '矩阵：\n%s\n的逆矩阵为：\n%s' % (m, I)

矩阵：
[[2 0 0]
 [0 4 0]
 [0 0 8]]
的逆矩阵为：
[[ 0.5    0.     0.   ]
 [ 0.     0.25   0.   ]
 [ 0.     0.     0.125]]


In [8]:
# coding=utf-8
import numpy as np

m = np.mat([[2, 0, 0], [0, 4, 0], [0, 0, 8]])
d = np.linalg.det(m)
print d

64.0


In [9]:
import numpy as np

m = np.mat([[2, 0, 0], [0, 4, 0], [0, 0, 8]])
i = m.I
d = np.linalg.det(m)
a = i * d
print a

[[ 32.   0.   0.]
 [  0.  16.   0.]
 [  0.   0.   8.]]
